fix server-gw links
AgoraIO/Docs pull request #53
Opened 2022-10-14 10:12 UTC by Kishan-Dhakan

- Resolves https://github.com/AgoraIO/Docs-Source/issues/555
- Resolves https://github.com/AgoraIO/Docs-Source/issues/643

2022-10-14 10:15 UTC, billy-the-fish requested changes
Can you align the version number please.

2022-10-14 10:15 UTC, billy-the-fish commented on data/sdks.js
>                label: 'Version 3.0.6 for Java',
Check the version number on maven please.

2022-10-14 10:18 UTC, Kishan-Dhakan commented on data/sdks.js
>                label: 'Version 3.0.6 for Java',
Resolved

2022-10-23 09:13 UTC, billy-the-fish approved these changes
LGTM

2022-10-23 09:29 UTC, merged